# Generated by Django 4.2.5 on 2023-09-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('qid', models.IntegerField()),
                ('qdate', models.DateField()),
                ('name', models.CharField(max_length=30)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=20)),
                ('today', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='dsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekno', models.IntegerField()),
                ('topic', models.CharField(max_length=30)),
                ('questions', models.ManyToManyField(null=True, to='myapi.question')),
            ],
        ),
    ]
