# Generated by Django 4.2.5 on 2023-09-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsa',
            name='questions',
            field=models.ManyToManyField(to='myapi.question'),
        ),
    ]
