# Generated by Django 4.2.5 on 2023-09-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_dsa_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsa',
            name='questions',
        ),
        migrations.AddField(
            model_name='dsa',
            name='q1',
            field=models.URLField(default='www.google.com', max_length=50),
        ),
        migrations.AddField(
            model_name='dsa',
            name='q2',
            field=models.URLField(default='www.google.com', max_length=50),
        ),
        migrations.AddField(
            model_name='dsa',
            name='q3',
            field=models.URLField(default='www.google.com', max_length=50),
        ),
        migrations.AddField(
            model_name='dsa',
            name='q4',
            field=models.URLField(default='www.google.com', max_length=50),
        ),
        migrations.AddField(
            model_name='dsa',
            name='q5',
            field=models.URLField(default='www.google.com', max_length=50),
        ),
        migrations.DeleteModel(
            name='question',
        ),
    ]
