# Generated by Django 4.2.5 on 2023-09-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_alter_dsa_q1_alter_dsa_q2_alter_dsa_q3_alter_dsa_q4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsa',
            name='id',
        ),
        migrations.AlterField(
            model_name='dsa',
            name='weekno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
