# Generated by Django 4.2.5 on 2023-09-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_alter_users_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
