# Generated by Django 4.2 on 2023-09-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_users_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='totalweek',
            field=models.IntegerField(default=0),
        ),
    ]
