# Generated by Django 4.2.5 on 2023-10-02 03:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_users_totalweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsa',
            name='d1',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dsa',
            name='d2',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dsa',
            name='d3',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dsa',
            name='d4',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dsa',
            name='d5',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
