# Generated by Django 4.2.5 on 2023-10-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_dsa_d1_dsa_d2_dsa_d3_dsa_d4_dsa_d5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsa',
            name='d1',
            field=models.DateField(verbose_name=['%d-%m-%Y']),
        ),
        migrations.AlterField(
            model_name='dsa',
            name='d2',
            field=models.DateField(verbose_name=['%d-%m-%Y']),
        ),
        migrations.AlterField(
            model_name='dsa',
            name='d3',
            field=models.DateField(verbose_name=['%d-%m-%Y']),
        ),
        migrations.AlterField(
            model_name='dsa',
            name='d4',
            field=models.DateField(verbose_name=['%d-%m-%Y']),
        ),
        migrations.AlterField(
            model_name='dsa',
            name='d5',
            field=models.DateField(verbose_name=['%d-%m-%Y']),
        ),
    ]
