# Generated by Django 4.2.5 on 2023-10-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0013_alter_dsa_d1_alter_dsa_d2_alter_dsa_d3_alter_dsa_d4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsa',
            name='d1',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dsa',
            name='d2',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dsa',
            name='d3',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dsa',
            name='d4',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dsa',
            name='d5',
            field=models.DateField(),
        ),
    ]
