# Generated by Django 4.2.5 on 2023-10-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0014_alter_dsa_d1_alter_dsa_d2_alter_dsa_d3_alter_dsa_d4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsa',
            name='r1',
            field=models.URLField(default='google.com', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dsa',
            name='r2',
            field=models.URLField(default='google.com', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dsa',
            name='r3',
            field=models.URLField(default='google.com', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dsa',
            name='r4',
            field=models.URLField(default='google.com', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dsa',
            name='r5',
            field=models.URLField(default='google.com', max_length=30),
            preserve_default=False,
        ),
    ]
