# Generated by Django 4.2.5 on 2023-10-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0015_dsa_r1_dsa_r2_dsa_r3_dsa_r4_dsa_r5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsa',
            name='q1',
            field=models.URLField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dsa',
            name='q2',
            field=models.URLField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dsa',
            name='q3',
            field=models.URLField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dsa',
            name='q4',
            field=models.URLField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dsa',
            name='q5',
            field=models.URLField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dsa',
            name='r1',
            field=models.URLField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='dsa',
            name='r2',
            field=models.URLField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='dsa',
            name='r3',
            field=models.URLField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='dsa',
            name='r4',
            field=models.URLField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='dsa',
            name='r5',
            field=models.URLField(blank=True, max_length=30),
        ),
    ]
