# Generated by Django 4.2.5 on 2023-10-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0016_alter_dsa_q1_alter_dsa_q2_alter_dsa_q3_alter_dsa_q4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsa',
            name='d1',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='dsa',
            name='d2',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='dsa',
            name='d3',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='dsa',
            name='d4',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='dsa',
            name='d5',
            field=models.DateField(blank=True),
        ),
    ]
