# Generated by Django 4.2.5 on 2023-10-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0018_alter_dsa_d1_alter_dsa_d2_alter_dsa_d3_alter_dsa_d4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
