# Generated by Django 4.2.7 on 2023-11-08 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0020_alter_dsa_q1_alter_dsa_q2_alter_dsa_q3_alter_dsa_q4_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='visits',
        ),
    ]
